spring.application.name=graphql-payments

# Enable GraphiQL
spring.graphql.graphiql.enabled=true

spring.graphql.http.path=/api/graphql

#now your local host is:
#http://localhost:8080/graphiql?path=/api/